apiVersion: v1
kind: Service
metadata:
  name: briefing-room
  namespace: briefing-room
  labels:
    app: briefing-room
spec:
  type: ClusterIP
  selector:
    app: briefing-room
  ports:
    - port: 80
      targetPort: 8080
