apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: salon-tls
  namespace: salon
spec:
  secretName: salon-tls
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  dnsNames:
    - salon.demo.managoat.com
