apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: salon-data
  namespace: salon
  labels:
    app: salon
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
