apiVersion: v1
kind: Service
metadata:
  name: drydock
  namespace: drydock
  labels:
    app: drydock
spec:
  type: ClusterIP
  selector:
    app: drydock
  ports:
    - port: 80
      targetPort: 8080
