apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: rounds-tls
  namespace: rounds
spec:
  secretName: rounds-tls
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  dnsNames:
    - rounds.demo.managoat.com
