apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: table-talk-tls
  namespace: table-talk
spec:
  secretName: table-talk-tls
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  dnsNames:
    - tables.inevitable.fyi
