apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: workbench-tls
  namespace: workbench
spec:
  secretName: workbench-tls
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  dnsNames:
    - workbench.inevitable.fyi
