apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: workbench-data
  namespace: workbench
  labels:
    app: workbench
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
