apiVersion: v1
kind: Service
metadata:
  name: watchtower
  namespace: watchtower
  labels:
    app: watchtower
spec:
  type: ClusterIP
  selector:
    app: watchtower
  ports:
    - port: 80
      targetPort: 8080
