apiVersion: v1
kind: Service
metadata:
  name: fountain-conversations
  namespace: fountain-conversations
  labels:
    app: fountain-conversations
spec:
  type: ClusterIP
  selector:
    app: fountain-conversations
  ports:
    - port: 80
      targetPort: 8080
