apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: repo-sage-tls
  namespace: managoat-demos
spec:
  secretName: repo-sage-tls
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  dnsNames:
    - repo-sage.demo.managoat.com
