apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: mend-tls
  namespace: managoat-demos
spec:
  secretName: mend-tls
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  dnsNames:
    - mend.demo.managoat.com
