apiVersion: v1
kind: Service
metadata:
  name: mend
  namespace: managoat-demos
  labels:
    app: mend
spec:
  type: ClusterIP
  selector:
    app: mend
  ports:
    - port: 80
      targetPort: 8080
