apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: paddock-data
  namespace: paddock
  labels:
    app: paddock
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
