apiVersion: v1
kind: Service
metadata:
  name: paddock
  namespace: paddock
  labels:
    app: paddock
spec:
  type: ClusterIP
  selector:
    app: paddock
  ports:
    - port: 80
      targetPort: 8080
