apiVersion: v1
kind: Service
metadata:
  name: workbench
  namespace: workbench
  labels:
    app: workbench
spec:
  type: ClusterIP
  selector:
    app: workbench
  ports:
    - port: 80
      targetPort: 8080
